### ISSUE TITLE
Where is 'datasets_tokenize.py'?

### ISSUE THREAD

**Issue by jhjangjh** [ex3ndr/supervoice-gpt#6]
Hi, thank you for your contribution!

I'm preparing a dataset now to train this GPT model.

But I can't find datasets_tokenize.py for `python ./datasets_tokenize.py` to tokenize datasets.

Can you tell me where it is or share this python file?

Or do you think It'll ok to skip this process and just use trained tokenizer(tokenizer_text.model) to train main supervoice-gpt model?

**Comment by ex3ndr** [comment]
There are no "datasets_tokenize.py" - it is tokenized online during training and inference.

**Comment by jhjangjh** [comment]
> There are no "datasets_tokenize.py" - it is tokenized online during training and inference.

Thank you for your quick reply!
If so, I think it would be better to modify item 6 of Readme's datasets part to prevent confusion.
